In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("../data/online_retail.csv", encoding="ISO-8859-1")

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom

In [6]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2023-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2023-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2023-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2023-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2023-12-09 12:50:00,4.95,12680.0,France

In [7]:
print("Dataset Shape:", df.shape)

Dataset Shape: (541909, 8)

In [8]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [9]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [10]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
df = df.dropna(subset=['CustomerID'])

In [14]:
df = df.dropna(subset=['Description'])

In [15]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [19]:

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [18]:
# Remove duplicate rows
df = df.drop_duplicates()

In [20]:
# Count cancelled invoices
cancelled = df[df['InvoiceNo'].astype(str).str.startswith('C')]

print("Cancelled Invoices:", cancelled.shape[0])

Cancelled Invoices: 8872

In [21]:
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

In [22]:
print("Cancelled invoices remaining:",
      df['InvoiceNo'].astype(str).str.startswith('C').sum())

Cancelled invoices remaining: 0

In [23]:
print("Rows with Quantity <= 0:", (df['Quantity'] <= 0).sum())

Rows with Quantity <= 0: 0

In [24]:
df = df[df['Quantity'] > 0]

In [25]:
print("Rows with Quantity <= 0:",
      (df['Quantity'] <= 0).sum())

Rows with Quantity <= 0: 0

In [26]:
print("Rows with UnitPrice <= 0:",
      (df['UnitPrice'] <= 0).sum())

Rows with UnitPrice <= 0: 40

In [27]:
df = df[df['UnitPrice'] > 0]

In [28]:
print("Rows with UnitPrice <= 0:",
      (df['UnitPrice'] <= 0).sum())

Rows with UnitPrice <= 0: 0

In [29]:
print("Final Dataset Shape:", df.shape)

print("\nRemaining Invalid Records:")
print("Cancelled:", df['InvoiceNo'].astype(str).str.startswith('C').sum())
print("Quantity <= 0:", (df['Quantity'] <= 0).sum())
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

Final Dataset Shape: (392692, 8)

Remaining Invalid Records:
Cancelled: 0
Quantity <= 0: 0
UnitPrice <= 0: 0

In [33]:
print(df['InvoiceDate'].dtype)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df['InvoiceDate'].dtype)

datetime64[ns]
datetime64[ns]

In [34]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [35]:
df[['Quantity', 'UnitPrice', 'TotalPrice']].head()

   Quantity  UnitPrice  TotalPrice
0         6       2.55       15.30
1         6       3.39       20.34
2         8       2.75       22.00
3         6       3.39       20.34
4         6       3.39       20.34

In [37]:
df.to_csv("../data/cleaned_online_retail.csv", index=False)